[package]
org = "saferoute"
name = "backend"
version = "0.1.0"
distribution = "2201.8.0"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.7.2"
[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.14.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.15.0"
