# Server Configuration (for main module)
serverPort = 8080
corsOrigins = ["http://localhost:3000"]

# Database Configuration (for backend.database module)
[backend.database]
host = "localhost"
port = 5432
name = "saferoute_db"
username = "postgres"
password = "123456"

# JWT Configuration (for backend.auth module)
[backend.auth]
jwtSecret = "pogVDNo+zysOxpiSYzqIp3FHuWimvX1bSj7uu674JoU="
jwtIssuer = "mindkraft-auth"
jwtAudience = "saferoute-users"
jwtExpiry=3600

smtpHost = "smtp.gmail.com"
smtpPort = 587
smtpUsername = "saferoute0@gmail.com"
smtpPassword = "rlaf wavf mjjx njpf"  
emailEnabled = true  

