# Example configuration for SafeRoute backend
# Copy this file to `Config.toml` and fill in your own values

# Server Configuration (for main module)
serverPort = 8080
corsOrigins = ["http://localhost:3000"]

# Database Configuration (for backend.database module)
[backend.database]
host = "<DB_HOST>"
port = <DB_PORT>
name = "<DB_NAME>"
username = "<DB_USER>"
password = "<DB_PASSWORD>"

# JWT Configuration (for backend.auth module)
[backend.auth]
jwtSecret = "<JWT_SECRET>"
jwtIssuer = "<JWT_ISSUER>"
jwtAudience = "<JWT_AUDIENCE>"
jwtExpiry = <JWT_EXPIRY>

smtpHost = "<SMTP_HOST>"
smtpPort = <SMTP_PORT>
smtpUsername = "<SMTP_USER>"
smtpPassword = "<SMTP_PASSWORD>"
emailEnabled = <EMAIL_ENABLED>
